# Generated by Django 2.2.12 on 2021-01-23 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20210122_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taginblog',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogs'),
        ),
    ]
